version: "3.8"
services:
  app:
    build:
      context: .
    container_name: fastapi_app
    ports:
      - "8000:8000" # Puerto interno para la aplicación
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    ports:
      - "80:80" # Puerto público de NGINX
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
